# Generated by Django 4.2.18 on 2025-03-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
