# Generated by Django 4.2.18 on 2025-03-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customadmin', '0005_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='user_groups', to='auth.group'),
        ),
    ]
