# Generated by Django 4.2.18 on 2025-03-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('html_body', models.TextField()),
                ('css_body', models.TextField()),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='documents/previews/')),
                ('mockup_image', models.ImageField(blank=True, null=True, upload_to='documents/mockups/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/files/')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('css', models.TextField(blank=True, null=True)),
                ('attribute_id', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('level', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.document')),
            ],
        ),
    ]
