# Generated by Django 4.2.18 on 2025-03-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_document_documentmeta_documentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_level',
            field=models.IntegerField(default=1),
        ),
    ]
