# Generated by Django 4.2.18 on 2025-04-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0012_alter_category_category_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentcategory',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='documentmeta',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='customadmin.category'),
        ),
    ]
