# Generated by Django 5.1.6 on 2025-04-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0013_rename_document_documentcategory_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verify_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
