# Generated by Django 4.2.18 on 2025-04-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0013_rename_document_documentcategory_document_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('font_family', models.CharField(max_length=255)),
            ],
        ),
    ]
