# Generated by Django 5.1.6 on 2025-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0014_user_email_verify_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verify_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
