# Generated by Django 5.1.6 on 2025-04-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0015_credituseshistory_creditearnhistory'),
        ('customadmin', '0015_user_password_reset_token_and_more'),
    ]

    operations = [
    ]
