# Generated by Django 5.1.6 on 2025-04-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0017_remove_document_file_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeaderFooterImage',
            new_name='DocumentHeaderFooterImage',
        ),
    ]
