# Generated by Django 4.2.18 on 2025-04-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0018_rename_headerfooterimage_documentheaderfooterimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentcategory',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='documentmeta',
            old_name='document_id',
            new_name='document',
        ),
    ]
