# Generated by Django 4.2.18 on 2025-04-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0019_rename_document_id_documentcategory_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
