# Generated by Django 5.1.6 on 2025-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0020_alter_font_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
