# Generated by Django 4.2.18 on 2025-04-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0021_documentheaderfooterimage_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentheaderfooterimage',
            name='is_default',
        ),
    ]
