# Generated by Django 5.1.6 on 2025-04-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0022_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_credit',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
