# Generated by Django 5.1.6 on 2025-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0023_user_user_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
