# Generated by Django 4.2.18 on 2025-04-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0023_documentheaderfooterimage_is_default'),
        ('customadmin', '0024_alter_user_user_credit'),
    ]

    operations = [
    ]
