# Generated by Django 5.1.6 on 2025-04-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0025_merge_20250421_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheaderfooterimage',
            name='css',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
