# Generated by Django 5.1.6 on 2025-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0026_documentheaderfooterimage_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheaderfooterimage',
            name='css',
            field=models.CharField(blank=True, null=True),
        ),
    ]
