# Generated by Django 5.1.6 on 2025-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0027_alter_documentheaderfooterimage_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='logo_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/files/'),
        ),
        migrations.AddField(
            model_name='document',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
