# Generated by Django 5.1.6 on 2025-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0028_document_email_document_location_document_logo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
