# Generated by Django 5.1.6 on 2025-04-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0029_alter_document_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(default=True, upload_to='documents/files/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='logo_path',
            field=models.FileField(default=True, upload_to='documents/files/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
