# Generated by Django 5.1.6 on 2025-04-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0030_alter_document_email_alter_document_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to='documents/files/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='logo_path',
            field=models.FileField(upload_to='documents/files/'),
        ),
    ]
