# Generated by Django 5.1.6 on 2025-05-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0031_alter_document_file_path_alter_document_logo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='css_body',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='html_body',
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentheaderfooterimage',
            name='footer',
            field=models.ImageField(upload_to='documents/previews/'),
        ),
        migrations.AlterField(
            model_name='documentheaderfooterimage',
            name='header',
            field=models.ImageField(upload_to='documents/previews/'),
        ),
    ]
