# Generated by Django 5.1.6 on 2025-05-06 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import datetime       


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0032_remove_document_css_body_remove_document_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('css', models.TextField(blank=True)),
                ('header_path', models.CharField(blank=True, max_length=255)),
                ('footer_path', models.CharField(blank=True, max_length=255)),
                ('download_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.now())),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.document')),
                ('document_hf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.documentheaderfooterimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
