# Generated by Django 5.1.6 on 2025-05-07 06:21

from django.db import migrations, models
from datetime import datetime 


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0033_downloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditearnhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
        ),
        migrations.AddField(
            model_name='credituseshistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
        ),
    ]
