# Generated by Django 5.1.6 on 2025-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0034_creditearnhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditearnhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credituseshistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
