# Generated by Django 5.1.6 on 2025-05-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0035_alter_creditearnhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='letterhead_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
