# Generated by Django 5.1.6 on 2025-05-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0036_document_letterhead_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditearnhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
