# Generated by Django 5.1.6 on 2025-05-08 07:58

from django.db import migrations, models
from datetime import datetime 


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0037_alter_creditearnhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditearnhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
        ),
        migrations.AlterField(
            model_name='credituseshistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
        ),
    ]
