# Generated by Django 5.1.6 on 2025-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0037_alter_creditearnhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditearnhistory',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='credituseshistory',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
