# Generated by Django 5.1.6 on 2025-05-08 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0038_alter_creditearnhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='letterhead_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditearnhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='credituseshistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='downloadhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
