# Generated by Django 4.2.18 on 2025-05-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0040_alter_creditearnhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
