# Generated by Django 4.2.18 on 2025-05-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0041_alter_downloadhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credituseshistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
