# Generated by Django 5.1.6 on 2025-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0042_alter_credituseshistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheaderfooterimage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
