# Generated by Django 5.2.1 on 2025-06-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0043_alter_documentheaderfooterimage_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditearnhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
